### ISSUE TITLE
Panic using expand CLI

### ISSUE THREAD

**Issue by aeneasr** [ory/keto#553]
**Describe the bug**

A panic when using expand CLI

**Reproducing the bug**

```
> keto expand owner projects some_id
neither flag --read-remote nor env var KETO_READ_REMOTE are set, falling back to 127.0.0.1:4466
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xf7ee77]

goroutine 1 [running]:
github.com/ory/keto/internal/expand.(*Tree).String(0x0, 0x13ec300, 0xc00000e018)
        /home/ory/internal/expand/tree.go:165 +0x37
github.com/ory/x/cmdx.PrintJSONAble(0xc00047a780, 0x13ea1e0, 0x0)
        /go/pkg/mod/github.com/ory/x@v0.0.212/cmdx/printing.go:119 +0x19e
github.com/ory/keto/cmd/expand.NewExpandCmd.func1(0xc00047a780, 0xc000263b90, 0x3, 0x3, 0x0, 0x0)
        /home/ory/cmd/expand/root.go:60 +0x30b
github.com/spf13/cobra.(*Command).execute(0xc00047a780, 0xc000263b60, 0x3, 0x3, 0xc00047a780, 0xc000263b60)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003ef680, 0xc00003a060, 0x1405518, 0xc0007d29c0)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:890
github.com/ory/keto/cmd.Execute()
        /home/ory/cmd/root.go:72 +0xbc
main.main()
        /home/ory/main.go:26 +0x52
```

**Expected behavior**

No panic

**Environment**

- Version: v0.6.0-alpha.1

**Additional context**

Reproducible in oasis

**Comment by zepatrik** [comment]
Looks like we did only fix JSON, not `.String()`
