### ISSUE TITLE
Running the keto binary on macOS fails

### ISSUE THREAD

**Issue by cojowy** [ory/keto#793]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/keto/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/keto/blob/master/CONTRIBUTING.md).
- [x] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The `keto` binary fails to run on macOS. I've tried to install it using brew, running `make install` and have downloaded it directly from the release artefacts. All fail with the same output.

### Reproducing the bug

1. Follow installation docs at https://www.ory.sh/keto/docs/install for any of `macOS`, `Download Binaries`, or `Building from source` on mac.
2. Run `keto help`

### Relevant log output

```shell
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff6d2b370a]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff6d2b370a
stack: frame={sp:0x7ffeefbff378, fp:0x7ffeefbff3c8} stack=[0x7ffeefb80418,0x7ffeefbff480)
0x00007ffeefbff278:  0x01007ffeefbff298  0x0000000000000004
0x00007ffeefbff288:  0x000000000000001f  0x00007fff6d2b370a
0x00007ffeefbff298:  0x0b01dfacedebac1e  0x0000000000000001
0x00007ffeefbff2a8:  0x0000000004035d51 <runtime.throw+0x0000000000000071>  0x00007ffeefbff348
0x00007ffeefbff2b8:  0x0000000004e74117  0x00007ffeefbff300
0x00007ffeefbff2c8:  0x0000000004036008 <runtime.fatalthrow.func1+0x0000000000000048>  0x000000000580bbc0
0x00007ffeefbff2d8:  0x0000000000000001  0x0000000000000001
0x00007ffeefbff2e8:  0x00007ffeefbff348  0x0000000004035d51 <runtime.throw+0x0000000000000071>
0x00007ffeefbff2f8:  0x000000000580bbc0  0x00007ffeefbff338
0x00007ffeefbff308:  0x0000000004035f90 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff318
0x00007ffeefbff318:  0x0000000004035fc0 <runtime.fatalthrow.func1+0x0000000000000000>  0x000000000580bbc0
0x00007ffeefbff328:  0x0000000004035d51 <runtime.throw+0x0000000000000071>  0x00007ffeefbff348
0x00007ffeefbff338:  0x00007ffeefbff368  0x0000000004035d51 <runtime.throw+0x0000000000000071>
0x00007ffeefbff348:  0x00007ffeefbff350  0x0000000004035d80 <runtime.throw.func1+0x0000000000000000>
0x00007ffeefbff358:  0x0000000004e853a8  0x000000000000002a
0x00007ffeefbff368:  0x00007ffeefbff3b8  0x000000000404c376 <runtime.sigpanic+0x0000000000000396>
0x00007ffeefbff378: <0x0000000004e853a8  0x000000000580bbc0
0x00007ffeefbff388:  0x00007ffeefbff3f8  0x0000000004026e26 <runtime.(*mheap).allocSpan+0x0000000000000546>
0x00007ffeefbff398:  0x0000000005825128  0x0000000000000002
0x00007ffeefbff3a8:  0x000000c000000008  0x0000000000040000
0x00007ffeefbff3b8:  0x00007ffeefbff400 !0x00007fff6d2b370a
0x00007ffeefbff3c8: >0x00007ffeefbff400  0x000000000575d000
0x00007ffeefbff3d8:  0x00000000000005fa  0x00000000043a9ca5 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005>
0x00007ffeefbff3e8:  0x000000000406b79f <runtime.syscall+0x000000000000001f>  0x000000c00073f5d8
0x00007ffeefbff3f8:  0x00007ffeefbff440  0x000000c00073f5a8
0x00007ffeefbff408:  0x00000000040695d0 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000001
0x00007ffeefbff418:  0x0000000004005800 <runtime.makechan+0x00000000000000c0>  0x5800000000001018
0x00007ffeefbff428:  0x000000000402cb65 <runtime.mProf_Malloc.func1+0x0000000000000025>  0x0000000005841378
0x00007ffeefbff438:  0x0000000000000a80  0x000000c0000001a0
0x00007ffeefbff448:  0x00000000040676e9 <runtime.systemstack+0x0000000000000049>  0x0000000000000004
0x00007ffeefbff458:  0x0000000004fcb080  0x000000000580bbc0
0x00007ffeefbff468:  0x00007ffeefbff4b8  0x00000000040675e5 <runtime.mstart+0x0000000000000005>
0x00007ffeefbff478:  0x000000000406759d <runtime.rt0_go+0x000000000000013d>
runtime.throw({0x4e853a8, 0x580bbc0})
	/usr/local/go/src/runtime/panic.go:1198 +0x71
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff6d2b370a
stack: frame={sp:0x7ffeefbff378, fp:0x7ffeefbff3c8} stack=[0x7ffeefb80418,0x7ffeefbff480)
0x00007ffeefbff278:  0x01007ffeefbff298  0x0000000000000004
0x00007ffeefbff288:  0x000000000000001f  0x00007fff6d2b370a
0x00007ffeefbff298:  0x0b01dfacedebac1e  0x0000000000000001
0x00007ffeefbff2a8:  0x0000000004035d51 <runtime.throw+0x0000000000000071>  0x00007ffeefbff348
0x00007ffeefbff2b8:  0x0000000004e74117  0x00007ffeefbff300
0x00007ffeefbff2c8:  0x0000000004036008 <runtime.fatalthrow.func1+0x0000000000000048>  0x000000000580bbc0
0x00007ffeefbff2d8:  0x0000000000000001  0x0000000000000001
0x00007ffeefbff2e8:  0x00007ffeefbff348  0x0000000004035d51 <runtime.throw+0x0000000000000071>
0x00007ffeefbff2f8:  0x000000000580bbc0  0x00007ffeefbff338
0x00007ffeefbff308:  0x0000000004035f90 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff318
0x00007ffeefbff318:  0x0000000004035fc0 <runtime.fatalthrow.func1+0x0000000000000000>  0x000000000580bbc0
0x00007ffeefbff328:  0x0000000004035d51 <runtime.throw+0x0000000000000071>  0x00007ffeefbff348
0x00007ffeefbff338:  0x00007ffeefbff368  0x0000000004035d51 <runtime.throw+0x0000000000000071>
0x00007ffeefbff348:  0x00007ffeefbff350  0x0000000004035d80 <runtime.throw.func1+0x0000000000000000>
0x00007ffeefbff358:  0x0000000004e853a8  0x000000000000002a
0x00007ffeefbff368:  0x00007ffeefbff3b8  0x000000000404c376 <runtime.sigpanic+0x0000000000000396>
0x00007ffeefbff378: <0x0000000004e853a8  0x000000000580bbc0
0x00007ffeefbff388:  0x00007ffeefbff3f8  0x0000000004026e26 <runtime.(*mheap).allocSpan+0x0000000000000546>
0x00007ffeefbff398:  0x0000000005825128  0x0000000000000002
0x00007ffeefbff3a8:  0x000000c000000008  0x0000000000040000
0x00007ffeefbff3b8:  0x00007ffeefbff400 !0x00007fff6d2b370a
0x00007ffeefbff3c8: >0x00007ffeefbff400  0x000000000575d000
0x00007ffeefbff3d8:  0x00000000000005fa  0x00000000043a9ca5 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005>
0x00007ffeefbff3e8:  0x000000000406b79f <runtime.syscall+0x000000000000001f>  0x000000c00073f5d8
0x00007ffeefbff3f8:  0x00007ffeefbff440  0x000000c00073f5a8
0x00007ffeefbff408:  0x00000000040695d0 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000001
0x00007ffeefbff418:  0x0000000004005800 <runtime.makechan+0x00000000000000c0>  0x5800000000001018
0x00007ffeefbff428:  0x000000000402cb65 <runtime.mProf_Malloc.func1+0x0000000000000025>  0x0000000005841378
0x00007ffeefbff438:  0x0000000000000a80  0x000000c0000001a0
0x00007ffeefbff448:  0x00000000040676e9 <runtime.systemstack+0x0000000000000049>  0x0000000000000004
0x00007ffeefbff458:  0x0000000004fcb080  0x000000000580bbc0
0x00007ffeefbff468:  0x00007ffeefbff4b8  0x00000000040675e5 <runtime.mstart+0x0000000000000005>
0x00007ffeefbff478:  0x000000000406759d <runtime.rt0_go+0x000000000000013d>
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:719 +0x396

goroutine 1 [syscall, locked to thread]:
syscall.syscall(0x43a9ca0, 0x1, 0x40487413, 0xc00073f668)
	/usr/local/go/src/runtime/sys_darwin.go:22 +0x3b fp=0xc00073f5d8 sp=0xc00073f5b8 pc=0x406605b
syscall.syscall(0x4075be6, 0xd0, 0xc00073f690, 0x4075b18)
	<autogenerated>:1 +0x26 fp=0xc00073f620 sp=0xc00073f5d8 pc=0x406bfa6
golang.org/x/sys/unix.ioctl(0x4e5032d, 0x4, 0x10000000000d0)
	/go/pkg/mod/golang.org/x/sys@v0.0.0-20210320140829-1e4c9ba3b0c4/unix/zsyscall_darwin_amd64.go:690 +0x39 fp=0xc00073f650 sp=0xc00073f620 pc=0x43a9599
golang.org/x/sys/unix.IoctlGetTermios(...)
	/go/pkg/mod/golang.org/x/sys@v0.0.0-20210320140829-1e4c9ba3b0c4/unix/ioctl.go:73
github.com/mattn/go-isatty.IsTerminal(0x4e5032d)
	/go/pkg/mod/github.com/mattn/go-isatty@v0.0.12/isatty_bsd.go:10 +0x50 fp=0xc00073f6c0 sp=0xc00073f650 pc=0x49fc970
github.com/fatih/color.init()
	/go/pkg/mod/github.com/fatih/color@v1.9.0/color.go:21 +0x7a fp=0xc00073f6f8 sp=0xc00073f6c0 pc=0x49fd2ba
runtime.doInit(0x576bb20)
	/usr/local/go/src/runtime/proc.go:6498 +0x123 fp=0xc00073f830 sp=0xc00073f6f8 pc=0x4045663
runtime.doInit(0x5779200)
	/usr/local/go/src/runtime/proc.go:6475 +0x71 fp=0xc00073f968 sp=0xc00073f830 pc=0x40455b1
runtime.doInit(0x5778980)
	/usr/local/go/src/runtime/proc.go:6475 +0x71 fp=0xc00073faa0 sp=0xc00073f968 pc=0x40455b1
runtime.doInit(0x5770420)
	/usr/local/go/src/runtime/proc.go:6475 +0x71 fp=0xc00073fbd8 sp=0xc00073faa0 pc=0x40455b1
runtime.doInit(0x576be80)
	/usr/local/go/src/runtime/proc.go:6475 +0x71 fp=0xc00073fd10 sp=0xc00073fbd8 pc=0x40455b1
runtime.doInit(0x5770d80)
	/usr/local/go/src/runtime/proc.go:6475 +0x71 fp=0xc00073fe48 sp=0xc00073fd10 pc=0x40455b1
runtime.doInit(0x5763a00)
	/usr/local/go/src/runtime/proc.go:6475 +0x71 fp=0xc00073ff80 sp=0xc00073fe48 pc=0x40455b1
runtime.main()
	/usr/local/go/src/runtime/proc.go:238 +0x1e6 fp=0xc00073ffe0 sp=0xc00073ff80 pc=0x40383a6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00073ffe8 sp=0xc00073ffe0 pc=0x40698c1

goroutine 5 [select]:
go.elastic.co/apm.(*Tracer).loop(0xc000242600)
	/go/pkg/mod/go.elastic.co/apm@v1.13.0/tracer.go:900 +0xc10
created by go.elastic.co/apm.newTracer
	/go/pkg/mod/go.elastic.co/apm@v1.13.0/tracer.go:449 +0x91e

goroutine 34 [chan receive]:
go.elastic.co/apm.(*Tracer).loop.func2()
	/go/pkg/mod/go.elastic.co/apm@v1.13.0/tracer.go:803 +0x21d
created by go.elastic.co/apm.(*Tracer).loop
	/go/pkg/mod/go.elastic.co/apm@v1.13.0/tracer.go:800 +0x40f

goroutine 9 [select]:
go.elastic.co/apm/transport.(*HTTPTransport).WatchConfig.func1()
	/go/pkg/mod/go.elastic.co/apm@v1.13.0/transport/http.go:398 +0x1ea
created by go.elastic.co/apm/transport.(*HTTPTransport).WatchConfig
	/go/pkg/mod/go.elastic.co/apm@v1.13.0/transport/http.go:390 +0x12f

goroutine 56 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x0)
	/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x6a
created by github.com/golang/glog.init.0
	/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x1c5

goroutine 57 [select]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc00038c3c0)
	/go/pkg/mod/github.com/dgraph-io/ristretto@v0.1.0/policy.go:102 +0x8c
created by github.com/dgraph-io/ristretto.newDefaultPolicy
	/go/pkg/mod/github.com/dgraph-io/ristretto@v0.1.0/policy.go:86 +0x15b

goroutine 58 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc0006be000)
	/go/pkg/mod/github.com/dgraph-io/ristretto@v0.1.0/cache.go:452 +0x16a
created by github.com/dgraph-io/ristretto.NewCache
	/go/pkg/mod/github.com/dgraph-io/ristretto@v0.1.0/cache.go:207 +0x46f

goroutine 59 [select]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc00038c440)
	/go/pkg/mod/github.com/dgraph-io/ristretto@v0.1.0/policy.go:102 +0x8c
created by github.com/dgraph-io/ristretto.newDefaultPolicy
	/go/pkg/mod/github.com/dgraph-io/ristretto@v0.1.0/policy.go:86 +0x15b

goroutine 60 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc0006be080)
	/go/pkg/mod/github.com/dgraph-io/ristretto@v0.1.0/cache.go:452 +0x16a
created by github.com/dgraph-io/ristretto.NewCache
	/go/pkg/mod/github.com/dgraph-io/ristretto@v0.1.0/cache.go:207 +0x46f
```

### Version

v0.7.0-alpha.1

### On which operating system are you observing this issue?

macOS

**Comment by aeneasr** [comment]
Updating golang.org/x/sys should fix this!
